version: '3'

networks:
  backend:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./projects:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
    depends_on:
      - php-7.1
      - php-7.3
      - mysql-8
      - mysql-5.7
      - redis
      - mongo
      - postgres
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/conf:/usr/local/etc/redis/redis.conf
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend

  mysql-5.7:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: unless-stopped
    volumes:
      - ./mysql-5.7/data:/var/lib/mysql
      - ./mysql-5.7/conf.d:/etc/mysql/conf.d
      - ./mysql-5.7/logs:/var/log/mysql/
      - ./mysql-5.7/dump:/dump
    ports:
      - "4307:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAG: dev
      SERVICE_NAME: mysql-5.7
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend

  mysql-8:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password --skip_name_resolve
    container_name: mysql-8
    restart: unless-stopped
    volumes:
      - ./mysql-8/data:/var/lib/mysql
      - ./mysql-8/conf.d:/etc/mysql/conf.d
      - ./mysql-8/logs:/var/log/mysql/
      - ./mysql-8/dump:/dump
    ports:
      - "4308:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAG: dev
      SERVICE_NAME: mysql-8
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend

  postgres:
    image: postgres:alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    environment:
      POSTGRES_DB: mif
      POSTGRES_USER: incidents
      POSTGRES_PASSWORD: secret
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
        - backend
    container_name: postgres

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
      - ./mongo/dump:/dump
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend
    container_name: mongo

  php-7.3:
    build:
      context: ./php-workspace
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_VERSION: '7.3'
        DOCKER_PHP_ENABLE_XDEBUG: ${DOCKER_PHP_ENABLE_XDEBUG}
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www
    container_name: php-7.3
    volumes:
      - ./projects:/var/www
      - ./php-ini/7.3/php.ini:/usr/local/etc/php/php.ini
      - ./php-workers/7.3/supervisor.d:/etc/supervisor.d
    ports:
      - "9003:9000"
    networks:
      - backend

  php-7.1:
    build:
      context: ./php-workspace
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_VERSION: '7.1'
        DOCKER_PHP_ENABLE_XDEBUG: ${DOCKER_PHP_ENABLE_XDEBUG}
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www
    container_name: php-7.1
    volumes:
      - ./projects:/var/www
      - ./php-ini/7.1/php.ini:/usr/local/etc/php/php.ini
      - ./php-workers/7.1/supervisor.d:/etc/supervisor.d
    ports:
      - "9001:9000"
    networks:
      - backend